platform :ios, '9.0'
target "LFBlog" do
pod 'ReactiveObjC'
pod 'Masonry'
pod 'Aspects'
pod 'SDWebImage'
pod 'JSONKit'
pod 'KafkaRefresh'
pod 'AFNetworking'
pod 'PYSearch'
pod 'YYKit'
pod 'TZImagePickerController'
pod 'BlocksKit'
pod 'MBProgressHUD'
end
use_frameworks!
